config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :improvements
     member do
       put "like", to: "projects#upvote"
      put "dislike", to: "projects#downvote"
  end
end


  resources :principles

  resources :books

  devise_for :users

  get 'welcome/index'

#  authenticated :user do |variable|
#    root 'dashboard#index', as: 'authenticated_root'
#  end

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
.container
	.row
		.col-md-12
			h1 Welcome to Our Michigan Ave
			p This website is your place to learn about the major developments that will reshape East Lansing and Lansing.
			p How will these projects improve our community?  How can you have a voice in this future?

			.container
				.row
					.col-md-12
						h4 This website has ideas to improve local development projects, principles that create a stronger vision for the future, and books about ideas that that have worked for other cities.

					.row
						.col-md-4
							h2 = link_to 'Projects', projects_path
							p These projects are transforming Greater Lansing

						.col-md-4
							h2 = link_to 'Great City Principles', principles_path
							p Share your ideas about what makes a Great City

						.col-md-4
							h2 = link_to 'Great City Books', books_path
							p Learn about designs that make cities productive, vibrant, and sustainable.

						