config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :improvements
     member do
       put "like", to: "projects#upvote"
      put "dislike", to: "projects#downvote"
  end
end


  resources :principles

  resources :books

  devise_for :users

  get 'welcome/index'

#  authenticated :user do |variable|
#    root 'dashboard#index', as: 'authenticated_root'
#  end

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :improvements
  validates_presence_of :title,:description
  validates_format_of :webpage, :with => URI::regexp(%w(http https))
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :upvote]
  respond_to :html, :xml, :json

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @improvements = @project.improvements
    respond_with(@improvements)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
  @project = Project.find(params[:id])
  @project.upvote_by current_user
  redirect_to projects_path
end
def downvote
  @project = Project.find(params[:id])
  @project.downvote_by current_user
redirect_to projects_path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :image, :webpage)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => "80", :rows => "10" %>
  </div>
 <div class ="form-group">
    Add Your <%= f.label :image %>:
    <%= f.file_field :image %>
    </div>
  <div class="field">
    <%= f.label :webpage %><br>
    <%= f.text_field :webpage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">

<h1>Editing Project</h1>

<%= render 'form' %>


<%= link_to 'Show', @project, class: "btn btn-link" %> |
<%= link_to 'Back', projects_path, class: "btn btn-link" %>

</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Greater Lansing Projects</h1>

<table>

  <tbody>
    <% @projects.each do |project| %>
      <tr>

        <td><h2><%= link_to project.title, project %> </h2></td>
        <td> <% if project.image.exists? %>
           <%= link_to (image_tag project.image.url(:medium), class: 'img-responsive img-medium') %>
        <% end %>
        </td>

        <% if user_signed_in? %>
             <%= link_to 'Edit', edit_project_path(project) %>
             <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>

        <td>  <h4>
            Submitted <%= time_ago_in_words(project.created_at) %>
          </h4> </td>
        <td> <%= link_to like_project_path(project), method: :put do %>
           Upvote 
         <% end %>  </td>

        <td> <%= link_to dislike_project_path(project), method: :put do %>
             Downvote
             </td>
             <td> <br><%= link_to 'Show', project %></td>
             <td> <br><%= link_to 'Edit', edit_project_path(project) %></td>
             <td> <br><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 </tr>
<% end %>
</td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if user_signed_in? %>
    <%= link_to 'New Project', new_project_path %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <h2> <%= @project.title %> </h2>

</p>

<p>
   <% if @project.image.exists? %>
        <%= link_to (image_tag @project.image.url(:medium), class: 'img-responsive img-medium') %>
    <% end %>
</p>

<p>
  <%= simple_format(@project.description) %>
</p>

<p>
  <%= link_to 'More Information about the Project', @project.webpage %>
</p>


<% if user_signed_in? %>
    <%= link_to 'Edit Project', edit_project_path(@project) %>
<% end %>
 
<h2>Improvement Ideas</h2>

<% @project.improvements.each do |improvement| %>
  <p>
	<b>
    <%= improvement.title.to_s.force_encoding("UTF-8") %>
    </b>
  </p>

  <p>
    <b>Author:</b>
    <%= improvement.author.to_s.force_encoding("UTF-8") %>
  </p> 

  <p>
    <b>Principle:</b>
    <%= improvement.principle %>
  </p>

  <p>
    <b>Description:</b>
    <%= simple_format(improvement.description) %>
  </p>

  <p>
      <% if improvement.image.exists? %>
         <%= link_to (image_tag improvement.image.url(:medium), class: 'img-responsive img-thumbnail') %>
      <% end %>
  </p>

<% if user_signed_in? %>
    <%= link_to 'Delete Improvement', project_improvement_path(@project, improvement),
    									method: :delete,
    									data: { confirm: "Are you sure?"} %>
<% end %>

<% end %>

<h2>Add an improvement:</h2>

<%= render "improvements/form" %>
<p>
<p>	

<%= link_to 'Back', projects_path, class: "btn btn-primary" %>

</div>

app/views/projects/show.html.old.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <h2> <%= @project.title %> </h2>

</p>

<p>
   <% if @project.image.exists? %>
        <%= link_to (image_tag @project.image.url(:medium), class: 'img-responsive img-medium') %>
    <% end %>
</p>

<p>
  <%= simple_format(@project.description) %>
</p>

<p>
  <%= link_to 'More Information about the Project', @project.webpage %>
</p>

<h2>Add an improvement:</h2>
<%= form_for([@project, @project.improvement.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :principle %><br />
    <%= f.text_field :principle %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
	
<h2>Improvements</h2>
<% @project.improvements.each do |improvement| %>
  <p>
    <b>Title:</b>
    <%= improvement.title %>
  </p>

  <p>
    <b>Author:</b>
    <%= improvement.author %>
  </p> 

  <p>
    <b>Principle:</b>
    <%= improvement.principle %>
  </p>

  <p>
    <b>Description:</b>
    <%= improvement.description %>
  </p>

<% end %>


<% if user_signed_in? %>
    <%= link_to 'Edit Project', edit_project_path(@project) %>
<% end %>

<%= link_to 'Back', projects_path %>

</div>