config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :improvements
     member do
       put "like", to: "projects#upvote"
      put "dislike", to: "projects#downvote"
  end
end


  resources :principles

  resources :books

  devise_for :users

  get 'welcome/index'

#  authenticated :user do |variable|
#    root 'dashboard#index', as: 'authenticated_root'
#  end

  root 'welcome#index'

end

app/models/principle.rb
class Principle < ActiveRecord::Base
  belongs_to :user
  has_many :improvements
  validates_presence_of :title, :author, :description
  validates_format_of :case_webpage, :with => URI::regexp(%w(http https))
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/principles_controller.rb
class PrinciplesController < ApplicationController
  before_action :set_principle, only: [:show, :edit, :update, :destroy]

  # GET /principles
  # GET /principles.json
  def index
    @principles = Principle.all
  end

  # GET /principles/1
  # GET /principles/1.json
  def show
  end

  # GET /principles/new
  def new
    @principle = Principle.new
  end

  # GET /principles/1/edit
  def edit
  end

  # POST /principles
  # POST /principles.json
  def create
    @principle = Principle.new(principle_params)

    respond_to do |format|
      if @principle.save
        format.html { redirect_to @principle, notice: 'Principle was successfully created.' }
        format.json { render :show, status: :created, location: @principle }
      else
        format.html { render :new }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principles/1
  # PATCH/PUT /principles/1.json
  def update
    respond_to do |format|
      if @principle.update(principle_params)
        format.html { redirect_to @principle, notice: 'Principle was successfully updated.' }
        format.json { render :show, status: :ok, location: @principle }
      else
        format.html { render :edit }
        format.json { render json: @principle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principles/1
  # DELETE /principles/1.json
  def destroy
    @principle.destroy
    respond_to do |format|
      format.html { redirect_to principles_url, notice: 'Principle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principle
      @principle = Principle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principle_params
      params.require(:principle).permit(:title, :author, :description, :image, :casestudy, :case_webpage)
    end
end

app/helpers/principles_helper.rb
module PrinciplesHelper
end

app/views/principles/_form.html.erb
<%= form_for(@principle, :html => { :multipart => true }) do |f| %>
  <% if @principle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@principle.errors.count, "error") %> prohibited this principle from being saved:</h2>

      <ul>
      <% @principle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => "80", :rows => "10" %>
  </div>
  <div class ="form-group">
    Add Your <%= f.label :image %>:
    <%= f.file_field :image %>
    </div>
    <div class="form-group">
    <%= f.label :casestudy %><br>
    <%= f.text_field :casestudy %>
  </div>
  <div class="form-group">
    <%= f.label :case_webpage %><br>
    <%= f.text_field :case_webpage %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/principles/edit.html.erb
<div class="container">
	<h1>Editing Principle</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @principle %> |
	<%= link_to 'Back', principles_path %>
</div class="container">

app/views/principles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Great City Principles</h1>
  <div class="row">
    <% @principles.each do |principle| %>

    <div class="col-md-4">

      <div class="thumbnail">
        <% if principle.image.exists? %>
            <%= link_to (image_tag principle.image.url(:thumb), class: 'img-responsive img-thumbnail') %>
        <% end %>
        <%= link_to principle.title, principle %>
        <br>
        <% if user_signed_in? %>
            <%= link_to 'Edit', edit_principle_path(principle) %>
            <%= link_to 'Destroy', principle, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %>
        <% end %>

      </div>

    </div>
    <% end %>

  </div>

<% if user_signed_in? %>
  <%= link_to 'New Principle', new_principle_path, class: "btn btn-link" %>
<% end %>

</div>

app/views/principles/new.html.erb
<div class="container">

	<h1>New Principle</h1>

	<%= render 'form' %>

	<%= link_to 'Back', principles_path %>
</div>	

app/views/principles/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <h2><%= @principle.title %></h2>
</p>

<p>
   <% if @principle.image.exists? %>
        <%= link_to (image_tag @principle.image.url(:medium), class: 'img-responsive img-medium') %>
    <% end %>
</p>

<p>
  <strong>Author:</strong>
  <%= @principle.author %>
</p>
<p>
  <%= simple_format(@principle.description) %>
</p>

<p>
  An example of this principle at work: <%= link_to @principle.casestudy, @principle.case_webpage %>
</p>

<% if user_signed_in? %>
    <%= link_to 'Edit Principle', edit_principle_path(@principle), class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', principles_path, class: "btn btn-primary" %>

</div>